// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmPqYMCIH7jsgrRmqQ0gOuas4rfJ-_Ao',
    appId: '1:496850234151:web:99ef968306a433e9429702',
    messagingSenderId: '496850234151',
    projectId: 'yammyapp-8f632',
    authDomain: 'yammyapp-8f632.firebaseapp.com',
    storageBucket: 'yammyapp-8f632.firebasestorage.app',
    measurementId: 'G-SXG6QJ3HH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBiVz-bwan3OpCHt2sB4CXRuVFHEOQTQ',
    appId: '1:496850234151:android:7f99c83c44a3772f429702',
    messagingSenderId: '496850234151',
    projectId: 'yammyapp-8f632',
    storageBucket: 'yammyapp-8f632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFA--UVoV5PL0yF7KanEpE02AYG-cosI',
    appId: '1:496850234151:ios:648972d581a6ef3f429702',
    messagingSenderId: '496850234151',
    projectId: 'yammyapp-8f632',
    storageBucket: 'yammyapp-8f632.firebasestorage.app',
    iosBundleId: 'com.example.yammyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOFA--UVoV5PL0yF7KanEpE02AYG-cosI',
    appId: '1:496850234151:ios:648972d581a6ef3f429702',
    messagingSenderId: '496850234151',
    projectId: 'yammyapp-8f632',
    storageBucket: 'yammyapp-8f632.firebasestorage.app',
    iosBundleId: 'com.example.yammyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAmPqYMCIH7jsgrRmqQ0gOuas4rfJ-_Ao',
    appId: '1:496850234151:web:d8316d87d9afd038429702',
    messagingSenderId: '496850234151',
    projectId: 'yammyapp-8f632',
    authDomain: 'yammyapp-8f632.firebaseapp.com',
    storageBucket: 'yammyapp-8f632.firebasestorage.app',
    measurementId: 'G-0YJZYD7YN3',
  );
}
